### ISSUE TITLE
[ERROR] 339: Couldn't find latitude and longitude

### ISSUE THREAD

**Issue by kyhos** [coskundeniz/google-ad-clicker-premium#2]
I installed it on MAC.
However, this error appears when I run **python ad_clicker.py**:

> python ad_clicker.py
 [ERROR] 339: Couldn't find latitude and longitude for 164.92.164.92! Retrying after 5 seconds...

I have already filled in the proxy list with port (ip:port), queries and config.json.

Any other files I should edit?
I've tried several proxies and none of them worked. I even tried some with SSL authentication, but they also failed.

**Is it possible to disable geolocation?**

**Comment by coskundeniz** [comment]
You can change the following line 
https://github.com/coskundeniz/google-ad-clicker-premium/blob/6ae629f5ce1be59f275eab5365df5d462271c412/utils.py#L475
as
lat, long, country_code, timezone = None, None, None, None
---
It must be related to your proxies especially if you are using free ones. I don't see a problem with good paid proxies.

**Comment by kyhos** [comment]
Thanks.
I edited it, but it showed this message.

> python run_ad_clicker.py
23-10-2024 09:35:03 [ INFO]  64: Running with 2 browsers...
23-10-2024 09:35:08 <<1>> [ INFO] 457: Using proxy: 190.107.237.18:999
Traceback (most recent call last):
  File "/Users/jorg/gac/ad_clicker.py", line 248, in <module>
    main()
  File "/Users/jorg/gac/ad_clicker.py", line 142, in main
    driver, country_code = create_webdriver(proxy, user_agent, plugin_folder_name)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jorg/gac/utils.py", line 483, in create_webdriver
    driver = CustomChrome(
             ^^^^^^^^^^^^^
  File "/Users/jorg/gac/env/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 258, in __init__
    self.patcher.auto()
  File "/Users/jorg/gac/env/lib/python3.11/site-packages/undetected_chromedriver/patcher.py", line 136, in auto
    most_recent = max(files, key=lambda f: f.stat().st_mtime)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence
23-10-2024 09:35:08 <<2>> [ INFO] 457: Using proxy: 13.56.246.195:80
Traceback (most recent call last):
  File "/Users/jorg/gac/ad_clicker.py", line 248, in <module>
    main()
  File "/Users/jorg/gac/ad_clicker.py", line 142, in main
    driver, country_code = create_webdriver(proxy, user_agent, plugin_folder_name)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jorg/gac/utils.py", line 483, in create_webdriver
    driver = CustomChrome(
             ^^^^^^^^^^^^^
  File "/Users/jorg/gac/env/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 258, in __init__
    self.patcher.auto()
  File "/Users/jorg/gac/env/lib/python3.11/site-packages/undetected_chromedriver/patcher.py", line 136, in auto
    most_recent = max(files, key=lambda f: f.stat().st_mtime)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence

**Comment by coskundeniz** [comment]
It is not related to this edit. If you need support, please buy one.
https://coskundeniz.github.io/ad_clicker/

**Comment by kyhos** [comment]
Ok. Thanks
I'll try to install from scratch again and try on Windows.

Do you think it might work if I reinstall undetected_chromedriver on this computer?

I don't know why this error occurred, because I followed the installation correctly and the command **python gui.py** works.

**Comment by coskundeniz** [comment]
1. Delete .MULTI_BROWSERS_IN_USE file.
2. Run python ad_clicker.py -q test
3. Continue with whatever command you want.

**Comment by kyhos** [comment]
> 1. Delete .MULTI_BROWSERS_IN_USE file.
> 2. Run python ad_clicker.py -q test
> 3. Continue with whatever command you want.

I deleted it, but it was already at zero bytes.
Even so, I deleted it and ran the command again.
The script generated it again, but always with zero bytes.

logs/adclicker.log:
> 23-10-2024 16:56:53 [DEBUG] run_ad_clicker.py: 44: Creating .MULTI_BROWSERS_IN_USE flag file...
23-10-2024 16:56:53 [ INFO] run_ad_clicker.py: 64: Running with 2 browsers...
23-10-2024 16:56:57 <<1>> [DEBUG] utils.py:576: Domains: ['www.booking.com', 'www.sixt.com']
23-10-2024 16:56:57 <<1>> [DEBUG] utils.py:145: user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
23-10-2024 16:56:57 <<1>> [DEBUG] utils.py:444: Maximizing window...
23-10-2024 16:56:57 <<1>> [ INFO] utils.py:457: Using proxy: xxx.xxx.87.100:3128
23-10-2024 16:56:57 <<1>> [DEBUG] utils.py:903: Getting locale language for None...
23-10-2024 16:56:57 <<1>> [DEBUG] utils.py:910: Locale language code for None: en
23-10-2024 16:56:58 <<2>> [DEBUG] utils.py:576: Domains: ['www.booking.com', 'www.sixt.com']
23-10-2024 16:56:58 <<2>> [DEBUG] utils.py:145: user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
23-10-2024 16:56:58 <<2>> [DEBUG] utils.py:444: Maximizing window...
23-10-2024 16:56:58 <<2>> [ INFO] utils.py:457: Using proxy: xxx.xxx.92.253:3128
23-10-2024 16:56:58 <<2>> [DEBUG] utils.py:903: Getting locale language for None...
23-10-2024 16:56:58 <<2>> [DEBUG] utils.py:910: Locale language code for None: en
