### ISSUE TITLE
Add troubleshooting to the documentation

### ISSUE THREAD

**Issue by noahfbrown** [coskundeniz/google-ad-clicker-premium#3]
The script works well. Congrats!

However, after running it for several hours, it always crashes.

I will post the most common errors that appear for me and I did not find a troubleshooting section.

/logs/adclicker.log

**set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.**
```
28-10-2024 06:00:50 <<1>> [ERROR] ad_clicker.py:216: Exception occurred. See the details in the log file.
**28-10-2024 06:00:50 <<1>> [DEBUG] ad_clicker.py:222: Exception: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.**
28-10-2024 06:00:50 <<1>> [DEBUG] ad_clicker.py:224: Exception details: 
  File "/adclicker/ad_clicker.py", line 165, in main
    ads, non_ad_links, shopping_ads = search_controller.search_for_ads(non_ad_domains=domains)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/adclicker/search_controller.py", line 185, in search_for_ads
    self._make_random_mouse_movements()
  File "/adclicker/search_controller.py", line 858, in _make_random_mouse_movements
    pyautogui.moveTo(screen_width / 2 - 300, screen_height / 2 - 200)
  File "/adclicker/env/lib/python3.11/site-packages/pyautogui/__init__.py", line 597, in wrapper
    failSafeCheck()
  File "/adclicker/env/lib/python3.11/site-packages/pyautogui/__init__.py", line 1722, in failSafeCheck
    raise FailSafeException(
```

**javascript error: no size and location**
`28-10-2024 07:17:16 <<1>> [DEBUG] ad_clicker.py:222: Exception: Message: javascript error: {"status":60,"value":"https://www.bloomberg.com/news/articles/2023-02-02/5-best-travel-credit-cards-of-2023-for-airport-lounge-access-miles-free-bags#:~:text=Bloomberg! has no size and location"}`

These errors crash the script or only load the Google search, open the results, but do not click on any ads and stop sending Telegram notifications.

Even after restarting the cycle, the script continues to crash.

Only after I manually press Ctrl + C, exit and send the command "python run_in_loop.py" again does it work again (click on the ads and resume sending Telegram notifications).

**Comment by coskundeniz** [comment]
Thanks for the advice.
I can add it for some of the errors that have solutions but some of the issues can be environment or os related. 
I will consider it anyway.

**Comment by noahfbrown** [comment]
Ok. No problem. Thanks!
What is fail safe?

Is it possible to randomize the screen size?

**Comment by coskundeniz** [comment]
https://stackoverflow.com/a/65381399

You can't change screen size.

**Comment by noahfbrown** [comment]
Ok, thanks.

Is it possible to use this (headless)? To run in the background and I can use my computer in the meantime?
https://developer.chrome.com/docs/chromium/headless

Suggestion: If there was a way to randomize the size (resolution) of Chrome, it would be interesting, as if they were devices with different screens.

**Comment by coskundeniz** [comment]
I added a troubleshooting section for common issues seen and handled exceptions for failsafe and click in code to prevent crash.

**Comment by noahfbrown** [comment]
> You should read the option explanations more carefully for the suggestion part. There is window_size option for that.

Sorry, I didn't express myself well.
If I define a size, it always stays that size and I have to change it manually.
I would like something random, for example, opening with a different size every time, automatically, to increase cloaking.



> I added a troubleshooting section for common issues seen and handled exceptions for failsafe and click in code to prevent crash.

Thank you!

**Comment by coskundeniz** [comment]
I don't have a plan to add randomized size. Since you are a software engineer, you should be able to change it for yourself. Thank you.
