### ISSUE TITLE
Python -m venv env Error:

### ISSUE THREAD

**Issue by jideswaggs** [coskundeniz/google-ad-clicker-premium#4]
[WinError 2] The system cannot find the file specified. Running from project directory. How to specify. Thanks
![17303135115308936629050969555424](https://github.com/user-attachments/assets/96434323-812b-4faf-8de5-ad8d0b70e1af)

**Comment by coskundeniz** [comment]
If python does not work, try py.
Check your paths too.

**Comment by jideswaggs** [comment]
python -m virtualenv env 
Works for windows users. Thanks
