### ISSUE TITLE
Run the script in the background and continue using the computer normally

### ISSUE THREAD

**Issue by noahfbrown** [coskundeniz/google-ad-clicker-premium#5]
Is there any way to run it in the background on Windows, with 2 different users or 2 desktops, or open Chrome in a minimized/hidden way but with navigation, scrolling and clicking working normally?

I have a spare PC just for this, but the computer with the most power (RAM and processing) is the one I also use for work. If I can run it in the background, that would be great for me, because I only use very light software for work and I could still open 8 more instances of Chrome on it.

Otherwise, I can only run 2 instances of Chrome on the old computer and only run it on this one at night and on the weekends.

Thanks!

**Comment by coskundeniz** [comment]
No, you should use a dedicated machine for it ideally. Alternatively, you can run it on multiple virtual machines on your resourceful machine so that you can minimize VirtualBox windows as they run.
